### ISSUE TITLE
Need to delete IMAGEDETAILS info

### ISSUE THREAD

**Issue by bruce-michelsen** [brettryan/confluence-attachment-tools-plugin#2]
We ran into an issue while upgrading Confluence. Turns out there were entries in the IMAGEDETAILS table that don't exist in the ATTACHMENTS table--most likely because a call to delete an attachment was only made in the ATTACHMENTS table.

Please see whether this tool should be removing entries from the IMAGEDETAILS table when removing attachments.

Thanks.
brucedmichelsen@yahoo.com

**Comment by brettryan** [comment]
Hi Bruce, sorry for the very late reply. I've just started looking at this plugin again. One thing about this is that the plugin only uses standard Confluence/Atlassian API calls which are abstracted away from the database model. To illustrate this I actually call [AttachmentManager.removeAttachmentVersionFromServer](https://docs.atlassian.com/confluence/latest/com/atlassian/confluence/pages/AttachmentManager.html), which if it is not updating the DB correctly then it would be an Atlassian bug.

I shall see about looking into this to try and replicate the issue you are having.

I have a version coming that is intended to fix the 5.7-5.9 incompatibility but am awaiting for a support response from Atlassian as the API changes from 5.7 onwards appear broken.

**Comment by jprusch** [comment]
Great that you're having a look at this excellent plugin. We're missing it since we had to upgrade to 5.7

I tried to do some fixing myself but as you pointed out the API changed somehow.

We're getting this error:

2015-07-28 00:00:00,120 ERROR [scheduler_Worker-9] [org.quartz.core.JobRunShell] run Job com.drunkendev.confluence.plugins.attachment-tools-plugin.purge-old-attachments-job threw an unhandled Exception:  net.sf.hibernate.LazyInitializationException: Hibernate lazy instantiation problem ..    com.drunkendev.confluence.plugins.attachments.PurgeAttachmentsJob.doExecute(PurgeAttachmentsJob.java:129) ... Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed

Let me know if you need some additional testing. I could do that on our test/staging environment running 5.9.6

Thanks,

Jan-Peter

**Comment by brettryan** [comment]
Please check [1.2.0-5.9-alpha-1](https://github.com/brettryan/confluence-attachment-tools-plugin/releases/tag/v1.2.0-5.9-alpha-1) for a first drop of a release which is compatible with 5.9.x.

NOTE: This is alpha and not production ready. If you choose to run it in production please test it on a test instance first.

I have been performing extensive testing thus far in a test confluence instance with tens of thousands of attachment versions which has not imposed any issues on the attachments themselves, however due to some internal changes within confluence there are known issues with confluence itself. Please check the release notes.

**Comment by jprusch** [comment]
Hi,
as promised I made a short test on our staging environment. Looks very good. I had no errors or exceptions. Debug logging was turned on. I set the threshold value to 500 attachments to delete per run.

Here are the last lines of our logging:

2016-03-16 07:55:48,196 INFO [scheduler_Worker-5] [confluence.plugins.attachments.PurgeAttachmentsJob] lambda$doExecute$11 3486 processable prior versions found for 9708 attachments.
2016-03-16 07:55:48,196 INFO [scheduler_Worker-5] [confluence.plugins.attachments.PurgeAttachmentsJob] lambda$doExecute$11 Visited 860 attachments averaging 190 ms per visit.
2016-03-16 07:55:48,196 INFO [scheduler_Worker-5] [confluence.plugins.attachments.PurgeAttachmentsJob] lambda$doExecute$11 A further 3485 versions are available for deleting.
2016-03-16 07:55:48,196 INFO [scheduler_Worker-5] [confluence.plugins.attachments.PurgeAttachmentsJob] lambda$doExecute$11 Attachment purging completed in 163788 ms.
2016-03-16 07:55:48,289 DEBUG [scheduler_Worker-5] [confluence.plugins.attachments.PurgeAttachmentsJob] lambda$mailResultsPlain$13 Mail Sent
2016-03-16 07:55:48,289 DEBUG [scheduler_Worker-5] [confluence.plugins.attachments.PurgeAttachmentsJob] lambda$doExecute$11 Purge attachments complete.
2016-03-16 07:55:48,679 WARN [scheduler_Worker-5] [confluence.util.profiling.DefaultActivityMonitor] close Exceeded the threshold of 60000 ms: ActivitySnapshot{startTime=1458111184313, threadId=35, threadName='scheduler_Worker-5', userId='', type='scheduled-job', summary='purge-old-attachments-job'}

Here the result line of the email summary:

## LOG:Logistik (http://xxxxxx/confluence/display/LOG)

Rekl.Fakt.QS.VSB (2) TO_DELETE: 1 [2 kB]
Rekl.Fakt.QS.VSB.png (2) TO_DELETE: 1 [25 kB]

3486processable prior versions found for 9708 attachments.Visited 860 attachments averaging 190 ms per visit.A further 3485 versions are available for deleting.Attachment purging completed in 163788 ms. 

Hope that supports you for further development.
Thanks for the excellent work.

Regards,

Jan-Peter

**Comment by brettryan** [comment]
Excellent. What was your search criteria? It looks like you may have not had any prior versions detected for deletion.

Just an fyi, the limit refers to the primary attachment versions visited, so if for example it were to delete 20 revisions on one attachment it will only count as one. I say this as 500 may be fairly high.

**Comment by brettryan** [comment]
My bad actually. I think you might have report mode turned on though.

**Comment by jprusch** [comment]
Yeah, sorry, report mode was turned on. Now (switched off) I get the NPEs on each attachment. Delete time for a single attachment is about 100 to 200 ms.

Log:
2016-03-17 07:48:58,824 DEBUG [scheduler_Worker-4] [confluence.plugins.attachments.PurgeAttachmentsJob] lambda$null$9 Attachment to remove 45056957
2016-03-17 07:48:58,980 ERROR [scheduler_Worker-4] [atlassian.event.internal.AsynchronousAbleEventDispatcher] run There was an exception thrown trying to dispatch event [com.atlassian.confluence.event.events.content.attachment.AttachmentVersionRemoveEvent[source=com.atlassian.confluence.pages.DefaultAttachmentManager@7b379259]] from the invoker [com.atlassian.confluence.event.ConfluenceListenerHandlersConfiguration$TimingListenerHandler$1$1@1b622d9a]
java.lang.RuntimeException: java.lang.NullPointerException
    at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:50)
Caused by: java.lang.NullPointerException
    at com.atlassian.confluence.plugins.files.notifications.FileContentEventListener.fileVersionDeleted(FileContentEventListener.java:233)
...
    at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:36)
    ... 97 more
2016-03-17 07:48:59,104 DEBUG [scheduler_Worker-4] [confluence.plugins.attachments.PurgeAttachmentsJob] lambda$null$9 Attachment to remove 45056958

Best regards,

Jan-Peter

**Comment by brettryan** [comment]
1.2.0 has now been released which brings with it support for 5.9 and 5.10. Thanks for your help in testing the alpha releases.
